CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340;

CREATE TABLE public.classification (
classification_id INT GENERATED BY DEFAULT AS IDENTITY,
classification_name CHARACTER VARYING NOT NULL,
CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE IF NOT EXISTS public.inventory (
inv_id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
inv_make CHARACTER VARYING NOT NULL,
inv_model CHARACTER VARYING NOT NULL,
inv_year CHARACTER(4) NOT NULL,
inv_description text NOT NULL,
inv_image CHARACTER VARYING NOT NULL,
inv_thumbnail CHARACTER VARYING NOT NULL,
inv_price numeric(9,0) NOT NULL,
inv_miles INT NOT NULL,
inv_color CHARACTER VARYING NOT NULL,
classification_id INT NOT NULL,
CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Create relationship between classification and inventory tables
ALTER TABLE IF EXISTS public.inventory
	ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id),
	REFERENCES public.classification (classification_id) MATCH SIMPLE,
	ON UPDATE CASCADE,
	ON DELETE NO ACTION;

INSERT INTO public.classification (classification_name)
VALUES ('Customs'), ('Sports'), ('SUV'), ('Truck'), ('Sedan')

UPDATE public.inventory SET inv_description = REPLACE(inv_description, 'the small interiors', 'a huge interior') WHERE inv_id = 10;
UPDATE public.inventory SET inv_image = REPLACE(inv_image, '/images', '/images/vehicles'), inv_thumbnail = REPLACE (inv_thumbnail, '/images', '/images/vehicles');